plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    id 'maven-publish'
}

if (System.getenv('BUILD_NUMBER') != null) {
    version += "." + System.getenv('BUILD_NUMBER')
}

base {
    archivesName = "${mod_id}-${minecraft_version}"
}

repositories {
    gradlePluginPortal()
    mavenLocal()

    maven {
        url "https://plugins.gradle.org/m2/"
    }

    maven {
        // location of the maven that hosts JEI files
        name = "Progwml6 maven"
        url = "https://dvs1.progwml6.com/files/maven/"
    }

    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.k-4u.nl"
    }

    maven {
        name = "CurseMaven"
        url = "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }

    maven {
        name = 'Sponge Snapshots'
        url = 'https://repo.spongepowered.org/repository/maven-public/'
    }

    maven {
        url 'https://jitpack.io'
    }

    maven {
        url 'https://maven.blamejared.com'
    }

    exclusiveContent {
        forRepositories(
                maven {
                    name = 'ParchmentMC'
                    url = 'https://maven.parchmentmc.org/'
                },
                maven {
                    name = "NeoForge"
                    url = 'https://maven.neoforged.net/releases'
                }
        )
        filter { includeGroup('org.parchmentmc.data') }
    }
}

loom {
    accessWidenerPath.set(file("src/main/resources/${mod_id}.accesswidener"))

    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
}

configurations {
    shade
    library
    library.extendsFrom(shade)
    implementation.extendsFrom(library)
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft_version}:${parchment_version}@zip")
    }

    modImplementation "net.fabricmc:fabric-loader:${project.fabric_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    //jaadec fork by yours truly to decode mp4 audio
    shade('com.github.AlexModGuy:JAADec:master-SNAPSHOT') {
        ['commons-logging', 'org.slf4j'].each {
            exclude group: "$it"
        }
    }

    //jcodec for decoding mp4 video
    shade('org.jcodec:jcodec:0.2.5') {
        exclude group: 'net.sourceforge.jaad.aac'
        ['commons-logging', 'org.slf4j', 'net.sourceforge.jaad.aac'].each {
            exclude group: "$it"
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

configurations {
    all*.exclude group: 'net.sourceforge.jaad', module: 'jcodec'
}

processResources {
    def expandProps = [
            minecraft_version    : project.minecraft_version,
            max_minecraft_version: project.max_minecraft_version,
            fabric_version       : project.fabric_version,
            fabric_api_version   : project.fabric_api_version,
            mod_id               : project.mod_id,
            mod_name             : project.mod_name,
            license              : project.license,
            version              : project.version,
            mod_author           : project.mod_author,
            description          : project.description,
            credits              : project.credits
    ]

    filesMatching(['pack.mcmeta', 'fabric.mod.json']) {
        expand expandProps
    }

    inputs.properties(expandProps)
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    inputs.property "archivesName", project.base.archivesName

    //classifier 'slim'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    afterEvaluate {
        configurations.shade.each { dep ->
            from(project.zipTree(dep)) {
                exclude 'META-INF', 'META-INF/**'
            }
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            url "file://" + System.getenv("local_maven")
        }
    }
}
